//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatiePRC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> IdAdministrator { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Student Student { get; set; }
    }
}
