//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatiePRC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaInvatamant
    {
        public FormaInvatamant()
        {
            this.Specializare = new HashSet<Specializare>();
        }
    
        public int IdFormaInvatamant { get; set; }
        public string DenumireFormaInvatamant { get; set; }
    
        public virtual ICollection<Specializare> Specializare { get; set; }
    }
}
