//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatiePRC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specializare
    {
        public Specializare()
        {
            this.Curs = new HashSet<Curs>();
            this.Student = new HashSet<Student>();
        }
    
        public int IdSpecializare { get; set; }
        public string DenumireSpecializare { get; set; }
        public int IdFacultate { get; set; }
        public int IdFormaInvatamant { get; set; }
    
        public virtual ICollection<Curs> Curs { get; set; }
        public virtual Facultate Facultate { get; set; }
        public virtual FormaInvatamant FormaInvatamant { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
