//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatiePRC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Cont = new HashSet<Cont>();
            this.Nota = new HashSet<Nota>();
        }
    
        public int IdStudent { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string CNP { get; set; }
        public System.DateTime DataNasterii { get; set; }
        public int IdSpecializare { get; set; }
        public int AnStudiu { get; set; }
        public string Grupa { get; set; }
    
        public virtual ICollection<Cont> Cont { get; set; }
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual Specializare Specializare { get; set; }
    }
}
